# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\andri\PycharmProjects\ProjectTeam\MainMenu2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainMenu(object):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(1971, 960)
        MainMenu.setMinimumSize(QtCore.QSize(1800, 900))
        MainMenu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainMenu.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, \n"
"    stop:0 rgba(57, 0, 95, 255), \n"
"    stop:0.427447 rgba(29, 43, 92, 235), \n"
"    stop:1 rgba(109, 55, 116, 255));")
        self.centralwidget = QtWidgets.QWidget(MainMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 20, 1921, 991))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setAutoFillBackground(False)
        self.tab.setStyleSheet("")
        self.tab.setObjectName("tab")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.tab)
        self.verticalScrollBar.setGeometry(QtCore.QRect(1890, 10, 20, 741))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.colorButton_0_70 = QtWidgets.QPushButton(self.tab)
        self.colorButton_0_70.setGeometry(QtCore.QRect(1270, 680, 42, 16))
        self.colorButton_0_70.setMouseTracking(True)
        self.colorButton_0_70.setToolTipDuration(2500)
        self.colorButton_0_70.setAutoFillBackground(False)
        self.colorButton_0_70.setStyleSheet("QPushButton {\n"
"    background-color: #90EE90;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid white;\n"
"}\n"
"QPushButton:checked {\n"
"    border: 3px solid black;\n"
"}\n"
"")
        self.colorButton_0_70.setText("")
        self.colorButton_0_70.setCheckable(True)
        self.colorButton_0_70.setChecked(False)
        self.colorButton_0_70.setObjectName("colorButton_0_70")
        self.colorButton_0_66 = QtWidgets.QPushButton(self.tab)
        self.colorButton_0_66.setGeometry(QtCore.QRect(650, 680, 41, 16))
        self.colorButton_0_66.setMouseTracking(True)
        self.colorButton_0_66.setToolTipDuration(2500)
        self.colorButton_0_66.setAutoFillBackground(False)
        self.colorButton_0_66.setStyleSheet("QPushButton {\n"
"    background-color: #000000;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 3px solid white;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    border: 3px solid black;\n"
"}\n"
"")
        self.colorButton_0_66.setText("")
        self.colorButton_0_66.setCheckable(True)
        self.colorButton_0_66.setChecked(False)
        self.colorButton_0_66.setObjectName("colorButton_0_66")
        self.colorButton_0_69 = QtWidgets.QPushButton(self.tab)
        self.colorButton_0_69.setGeometry(QtCore.QRect(1180, 680, 41, 16))
        self.colorButton_0_69.setMouseTracking(True)
        self.colorButton_0_69.setToolTipDuration(2500)
        self.colorButton_0_69.setAutoFillBackground(False)
        self.colorButton_0_69.setStyleSheet("QPushButton {\n"
"    background-color: #FFC0CB;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid white;\n"
"}\n"
"QPushButton:checked {\n"
"    border: 3px solid black;\n"
"}\n"
"")
        self.colorButton_0_69.setText("")
        self.colorButton_0_69.setCheckable(True)
        self.colorButton_0_69.setChecked(False)
        self.colorButton_0_69.setObjectName("colorButton_0_69")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(1120, 670, 241, 91))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    border: 0.5px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 3px solid white;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0,\n"
"    stop:0 rgba(70, 35, 105, 200),\n"
"    stop:0.427447 rgba(60, 75, 135, 200),\n"
"    stop:1 rgba(120, 75, 135, 220));\n"
"}")
        self.pushButton_3.setText("")
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.radioButton_1 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_1.setGeometry(QtCore.QRect(810, 630, 111, 31))
        self.radioButton_1.setStyleSheet("background:transparent;\n"
"color:white;\n"
"font-weight:bold;")
        self.radioButton_1.setObjectName("radioButton_1")
        self.colorButton_0_68 = QtWidgets.QPushButton(self.tab)
        self.colorButton_0_68.setGeometry(QtCore.QRect(695, 680, 42, 16))
        self.colorButton_0_68.setMouseTracking(True)
        self.colorButton_0_68.setToolTipDuration(2500)
        self.colorButton_0_68.setAutoFillBackground(False)
        self.colorButton_0_68.setStyleSheet("QPushButton {\n"
"    background-color: #364135;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Коли кнопка в стані наведення */\n"
"QPushButton:hover {\n"
"    border: 3px solid white;\n"
"}\n"
"\n"
"/* Коли кнопка натиснута й активна */\n"
"QPushButton:checked {\n"
"    border: 3px solid black;\n"
"}\n"
"")
        self.colorButton_0_68.setText("")
        self.colorButton_0_68.setCheckable(True)
        self.colorButton_0_68.setChecked(False)
        self.colorButton_0_68.setObjectName("colorButton_0_68")
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_3.setGeometry(QtCore.QRect(1060, 630, 111, 31))
        self.radioButton_3.setStyleSheet("background:transparent;\n"
"color: white;\n"
"font-weight:bold;")
        self.radioButton_3.setObjectName("radioButton_3")
        self.pushButton_1 = QtWidgets.QPushButton(self.tab)
        self.pushButton_1.setGeometry(QtCore.QRect(591, 670, 241, 91))
        self.pushButton_1.setStyleSheet("QPushButton {\n"
"    border: 0.5px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 3px solid white;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0,\n"
"    stop:0 rgba(70, 35, 105, 200),\n"
"    stop:0.427447 rgba(60, 75, 135, 200),\n"
"    stop:1 rgba(120, 75, 135, 220));\n"
"\n"
"}")
        self.pushButton_1.setText("")
        self.pushButton_1.setCheckable(True)
        self.pushButton_1.setObjectName("pushButton_1")
        self.colorButton_3_66 = QtWidgets.QPushButton(self.tab)
        self.colorButton_3_66.setGeometry(QtCore.QRect(1000, 680, 42, 16))
        self.colorButton_3_66.setMouseTracking(True)
        self.colorButton_3_66.setToolTipDuration(2500)
        self.colorButton_3_66.setAutoFillBackground(False)
        self.colorButton_3_66.setStyleSheet("QPushButton {\n"
"    background-color: #C71585;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid white;\n"
"}\n"
"QPushButton:checked {\n"
"    border: 3px solid black;\n"
"}\n"
"")
        self.colorButton_3_66.setText("")
        self.colorButton_3_66.setCheckable(True)
        self.colorButton_3_66.setChecked(False)
        self.colorButton_3_66.setObjectName("colorButton_3_66")
        self.colorButton_0_71 = QtWidgets.QPushButton(self.tab)
        self.colorButton_0_71.setGeometry(QtCore.QRect(1225, 680, 41, 16))
        self.colorButton_0_71.setMouseTracking(True)
        self.colorButton_0_71.setToolTipDuration(2500)
        self.colorButton_0_71.setAutoFillBackground(False)
        self.colorButton_0_71.setStyleSheet("QPushButton {\n"
"    background-color: #7FFFD4;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 3px solid white;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    border: 3px solid black;\n"
"}\n"
"")
        self.colorButton_0_71.setText("")
        self.colorButton_0_71.setCheckable(True)
        self.colorButton_0_71.setChecked(False)
        self.colorButton_0_71.setObjectName("colorButton_0_71")
        self.colorButton_0_67 = QtWidgets.QPushButton(self.tab)
        self.colorButton_0_67.setGeometry(QtCore.QRect(741, 680, 41, 16))
        self.colorButton_0_67.setMouseTracking(True)
        self.colorButton_0_67.setToolTipDuration(2500)
        self.colorButton_0_67.setAutoFillBackground(False)
        self.colorButton_0_67.setStyleSheet("QPushButton {\n"
"    background-color: #4B0082;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 3px solid white;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    border: 3px solid black;\n"
"}\n"
"")
        self.colorButton_0_67.setText("")
        self.colorButton_0_67.setCheckable(True)
        self.colorButton_0_67.setChecked(False)
        self.colorButton_0_67.setObjectName("colorButton_0_67")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_2.setGeometry(QtCore.QRect(940, 630, 111, 31))
        self.radioButton_2.setStyleSheet("background:transparent;\n"
"color:white;\n"
"font-weight:bold;")
        self.radioButton_2.setObjectName("radioButton_2")
        self.colorButton_3_67 = QtWidgets.QPushButton(self.tab)
        self.colorButton_3_67.setGeometry(QtCore.QRect(955, 680, 41, 16))
        self.colorButton_3_67.setMouseTracking(True)
        self.colorButton_3_67.setToolTipDuration(2500)
        self.colorButton_3_67.setAutoFillBackground(False)
        self.colorButton_3_67.setStyleSheet("QPushButton {\n"
"    background-color: #4B0082;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid white;\n"
"}\n"
"QPushButton:checked {\n"
"    border: 3px solid black;\n"
"}\n"
"")
        self.colorButton_3_67.setText("")
        self.colorButton_3_67.setCheckable(True)
        self.colorButton_3_67.setChecked(False)
        self.colorButton_3_67.setObjectName("colorButton_3_67")
        self.colorButton_3_68 = QtWidgets.QPushButton(self.tab)
        self.colorButton_3_68.setGeometry(QtCore.QRect(910, 680, 41, 16))
        self.colorButton_3_68.setMouseTracking(True)
        self.colorButton_3_68.setToolTipDuration(2500)
        self.colorButton_3_68.setAutoFillBackground(False)
        self.colorButton_3_68.setStyleSheet("QPushButton {\n"
"    background-color: #0F52BA;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    border: 3px solid white;\n"
"}\n"
"QPushButton:checked {\n"
"    border: 3px solid black;\n"
"}\n"
"")
        self.colorButton_3_68.setText("")
        self.colorButton_3_68.setCheckable(True)
        self.colorButton_3_68.setChecked(False)
        self.colorButton_3_68.setObjectName("colorButton_3_68")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(855, 670, 241, 91))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border: 0.5px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 3px solid white;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0,\n"
"    stop:0 rgba(70, 35, 105, 200),\n"
"    stop:0.427447 rgba(60, 75, 135, 200),\n"
"    stop:1 rgba(120, 75, 135, 220));\n"
"}")
        self.pushButton_2.setText("")
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.b_processImage = QtWidgets.QPushButton(self.tab)
        self.b_processImage.setGeometry(QtCore.QRect(880, 770, 171, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 137, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 137, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 137, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.b_processImage.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.b_processImage.setFont(font)
        self.b_processImage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.b_processImage.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.b_processImage.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0.3);\n"
"    border:none;\n"
"    border-radius: 10px;\n"
"    padding: 6px 12px;\n"
"    color: #fff;\n"
"    font-weight:bold;\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgba(235, 225, 225, 0.9);\n"
"    background-color: rgba(200, 200, 200, 0.5);\n"
"    text-decoration: underline;\n"
"}")
        self.b_processImage.setObjectName("b_processImage")
        self.L_ProcImage = QtWidgets.QLabel(self.tab)
        self.L_ProcImage.setGeometry(QtCore.QRect(980, 110, 741, 511))
        self.L_ProcImage.setStyleSheet("background:white;")
        self.L_ProcImage.setText("")
        self.L_ProcImage.setObjectName("L_ProcImage")
        self.b_SaveProcImage0 = QtWidgets.QPushButton(self.tab)
        self.b_SaveProcImage0.setGeometry(QtCore.QRect(1600, 80, 81, 28))
        self.b_SaveProcImage0.setStyleSheet("background:purple;\n"
"color:white;\n"
"")
        self.b_SaveProcImage0.setObjectName("b_SaveProcImage0")
        self.b_deleteProcImage0 = QtWidgets.QPushButton(self.tab)
        self.b_deleteProcImage0.setGeometry(QtCore.QRect(1690, 80, 31, 28))
        self.b_deleteProcImage0.setStyleSheet("background:purple;\n"
"color:white;\n"
"")
        self.b_deleteProcImage0.setObjectName("b_deleteProcImage0")
        self.l_OrigImage = QtWidgets.QLabel(self.tab)
        self.l_OrigImage.setGeometry(QtCore.QRect(200, 110, 741, 511))
        self.l_OrigImage.setStyleSheet("background:white;")
        self.l_OrigImage.setText("")
        self.l_OrigImage.setObjectName("l_OrigImage")
        self.b_deleteOrigImage0 = QtWidgets.QPushButton(self.tab)
        self.b_deleteOrigImage0.setGeometry(QtCore.QRect(910, 80, 31, 28))
        self.b_deleteOrigImage0.setStyleSheet("background:purple;\n"
"color:white;\n"
"")
        self.b_deleteOrigImage0.setObjectName("b_deleteOrigImage0")
        self.b_show = QtWidgets.QPushButton(self.tab)
        self.b_show.setGeometry(QtCore.QRect(770, 20, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.b_show.setFont(font)
        self.b_show.setStyleSheet("background:purple;\n"
"color:white;\n"
"")
        self.b_show.setObjectName("b_show")
        self.b_hide = QtWidgets.QPushButton(self.tab)
        self.b_hide.setGeometry(QtCore.QRect(980, 20, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.b_hide.setFont(font)
        self.b_hide.setStyleSheet("background:purple;\n"
"color:white;\n"
"")
        self.b_hide.setObjectName("b_hide")
        self.b_AddOrigImage0 = QtWidgets.QPushButton(self.tab)
        self.b_AddOrigImage0.setGeometry(QtCore.QRect(870, 80, 31, 28))
        self.b_AddOrigImage0.setStyleSheet("background:purple;\n"
"color:white;\n"
"")
        self.b_AddOrigImage0.setObjectName("b_AddOrigImage0")
        self.pushButton_3.raise_()
        self.pushButton_2.raise_()
        self.pushButton_1.raise_()
        self.verticalScrollBar.raise_()
        self.colorButton_0_70.raise_()
        self.colorButton_0_66.raise_()
        self.colorButton_0_69.raise_()
        self.radioButton_1.raise_()
        self.colorButton_0_68.raise_()
        self.radioButton_3.raise_()
        self.colorButton_3_66.raise_()
        self.colorButton_0_71.raise_()
        self.colorButton_0_67.raise_()
        self.radioButton_2.raise_()
        self.colorButton_3_67.raise_()
        self.colorButton_3_68.raise_()
        self.b_processImage.raise_()
        self.L_ProcImage.raise_()
        self.b_SaveProcImage0.raise_()
        self.b_deleteProcImage0.raise_()
        self.l_OrigImage.raise_()
        self.b_deleteOrigImage0.raise_()
        self.b_show.raise_()
        self.b_hide.raise_()
        self.b_AddOrigImage0.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        self.frame_3.setGeometry(QtCore.QRect(970, 640, 431, 211))
        self.frame_3.setStyleSheet("border: 2px solid rgba(235, 225, 225, 0.9);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_20 = QtWidgets.QLabel(self.frame_3)
        self.label_20.setEnabled(False)
        self.label_20.setGeometry(QtCore.QRect(20, 20, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background:transparent;\n"
"color:white;\n"
"font-weight:bold;\n"
"border:none;")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.b_ProcImageDecryptedText_2 = QtWidgets.QPushButton(self.frame_3)
        self.b_ProcImageDecryptedText_2.setGeometry(QtCore.QRect(220, 20, 191, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 137, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 137, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 137, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.b_ProcImageDecryptedText_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.b_ProcImageDecryptedText_2.setFont(font)
        self.b_ProcImageDecryptedText_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.b_ProcImageDecryptedText_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.b_ProcImageDecryptedText_2.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0.3);\n"
"    border:none;\n"
"    border-radius: 10px;\n"
"    padding: 6px 12px;\n"
"    color: #fff;\n"
"    font-weight:bold;\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgba(235, 225, 225, 0.9);\n"
"    background-color: rgba(200, 200, 200, 0.5);\n"
"    text-decoration: underline;\n"
"}")
        self.b_ProcImageDecryptedText_2.setObjectName("b_ProcImageDecryptedText_2")
        self.te_DecryptedText_2 = QtWidgets.QTextEdit(self.frame_3)
        self.te_DecryptedText_2.setGeometry(QtCore.QRect(20, 70, 391, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.te_DecryptedText_2.setFont(font)
        self.te_DecryptedText_2.setStyleSheet("color:white;")
        self.te_DecryptedText_2.setObjectName("te_DecryptedText_2")
        self.b_deleteProcImageEnc = QtWidgets.QPushButton(self.tab_2)
        self.b_deleteProcImageEnc.setGeometry(QtCore.QRect(1680, 40, 31, 28))
        self.b_deleteProcImageEnc.setStyleSheet("background:purple;\n"
"color:white;\n"
"")
        self.b_deleteProcImageEnc.setObjectName("b_deleteProcImageEnc")
        self.b_SaveProcImageEnc = QtWidgets.QPushButton(self.tab_2)
        self.b_SaveProcImageEnc.setGeometry(QtCore.QRect(1590, 40, 81, 28))
        self.b_SaveProcImageEnc.setStyleSheet("background:purple;\n"
"color:white;\n"
"")
        self.b_SaveProcImageEnc.setObjectName("b_SaveProcImageEnc")
        self.frame_2 = QtWidgets.QFrame(self.tab_2)
        self.frame_2.setGeometry(QtCore.QRect(520, 640, 431, 151))
        self.frame_2.setStyleSheet("border: 2px solid rgba(235, 225, 225, 0.9);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.le_EncryptedText = QtWidgets.QLineEdit(self.frame_2)
        self.le_EncryptedText.setEnabled(True)
        self.le_EncryptedText.setGeometry(QtCore.QRect(20, 80, 391, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.le_EncryptedText.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.le_EncryptedText.setFont(font)
        self.le_EncryptedText.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.le_EncryptedText.setAutoFillBackground(False)
        self.le_EncryptedText.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(255, 255, 255, 0.3);\n"
"    border:none;\n"
"    border-radius: 10px;\n"
"    padding: 6px 12px;\n"
"    color: #fff;\n"
"    font-weight:bold;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgba(235, 225, 225, 0.9);\n"
"    background-color: rgba(200, 200, 200, 0.5);\n"
"}")
        self.le_EncryptedText.setText("")
        self.le_EncryptedText.setMaxLength(50)
        self.le_EncryptedText.setFrame(False)
        self.le_EncryptedText.setReadOnly(False)
        self.le_EncryptedText.setObjectName("le_EncryptedText")
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setEnabled(False)
        self.label_19.setGeometry(QtCore.QRect(20, 30, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setMouseTracking(True)
        self.label_19.setStyleSheet("background:transparent;\n"
"color:white;\n"
"font-weight:bold;\n"
"border:none;")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.b_ProcImageEncryptedText = QtWidgets.QPushButton(self.frame_2)
        self.b_ProcImageEncryptedText.setGeometry(QtCore.QRect(220, 30, 191, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 137, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 137, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 137, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.b_ProcImageEncryptedText.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.b_ProcImageEncryptedText.setFont(font)
        self.b_ProcImageEncryptedText.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.b_ProcImageEncryptedText.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.b_ProcImageEncryptedText.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0.3);\n"
"    border:none;\n"
"    border-radius: 10px;\n"
"    padding: 6px 12px;\n"
"    color: #fff;\n"
"    font-weight:bold;\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgba(235, 225, 225, 0.9);\n"
"    background-color: rgba(200, 200, 200, 0.5);\n"
"    text-decoration: underline;\n"
"}")
        self.b_ProcImageEncryptedText.setObjectName("b_ProcImageEncryptedText")
        self.b_deleteOrigImageEnc = QtWidgets.QPushButton(self.tab_2)
        self.b_deleteOrigImageEnc.setGeometry(QtCore.QRect(920, 40, 31, 28))
        self.b_deleteOrigImageEnc.setStyleSheet("background:purple;\n"
"color:white;\n"
"")
        self.b_deleteOrigImageEnc.setObjectName("b_deleteOrigImageEnc")
        self.b_AddOrigImageEnc = QtWidgets.QPushButton(self.tab_2)
        self.b_AddOrigImageEnc.setGeometry(QtCore.QRect(880, 40, 31, 28))
        self.b_AddOrigImageEnc.setStyleSheet("background:purple;\n"
"color:white;\n"
"")
        self.b_AddOrigImageEnc.setObjectName("b_AddOrigImageEnc")
        self.l_ProcImageEnc = QtWidgets.QLabel(self.tab_2)
        self.l_ProcImageEnc.setGeometry(QtCore.QRect(970, 70, 741, 551))
        self.l_ProcImageEnc.setStyleSheet("background:white;")
        self.l_ProcImageEnc.setText("")
        self.l_ProcImageEnc.setObjectName("l_ProcImageEnc")
        self.l_OrigImageEnc = QtWidgets.QLabel(self.tab_2)
        self.l_OrigImageEnc.setGeometry(QtCore.QRect(210, 70, 741, 551))
        self.l_OrigImageEnc.setStyleSheet("background:white;")
        self.l_OrigImageEnc.setText("")
        self.l_OrigImageEnc.setObjectName("l_OrigImageEnc")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setGeometry(QtCore.QRect(110, 120, 491, 91))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(110, 250, 491, 91))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(110, 400, 491, 91))
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.tab_4, "")
        self.b_exit = QtWidgets.QPushButton(self.centralwidget)
        self.b_exit.setGeometry(QtCore.QRect(1800, 10, 81, 28))
        self.b_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.b_exit.setMouseTracking(True)
        self.b_exit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.b_exit.setStyleSheet("color:white;\n"
"font-weight:bold;")
        self.b_exit.setObjectName("b_exit")
        self.la_username = QtWidgets.QLabel(self.centralwidget)
        self.la_username.setGeometry(QtCore.QRect(1564, 10, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.la_username.setFont(font)
        self.la_username.setStyleSheet("background:transparent;\n"
"color:white;\n"
"")
        self.la_username.setObjectName("la_username")
        self.b_exit.raise_()
        self.la_username.raise_()
        self.tabWidget.raise_()
        MainMenu.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainMenu)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "Main Menu"))
        self.colorButton_0_70.setToolTip(_translate("MainMenu", "Світло-зелений"))
        self.colorButton_0_66.setToolTip(_translate("MainMenu", "Чорний"))
        self.colorButton_0_69.setToolTip(_translate("MainMenu", "Рожевий"))
        self.radioButton_1.setText(_translate("MainMenu", "Крива Коха"))
        self.colorButton_0_68.setToolTip(_translate("MainMenu", "Вугільний"))
        self.radioButton_3.setText(_translate("MainMenu", "Гра життя"))
        self.colorButton_3_66.setToolTip(_translate("MainMenu", "Темно-рожевий"))
        self.colorButton_0_71.setToolTip(_translate("MainMenu", "Аквамарин"))
        self.colorButton_0_67.setToolTip(_translate("MainMenu", "Темно-пурпурний"))
        self.radioButton_2.setText(_translate("MainMenu", "Шум Перліна"))
        self.colorButton_3_67.setToolTip(_translate("MainMenu", "Індиго"))
        self.colorButton_3_68.setToolTip(_translate("MainMenu", "Сапфіровий"))
        self.b_processImage.setText(_translate("MainMenu", "Обробити фото"))
        self.b_SaveProcImage0.setText(_translate("MainMenu", "Зберегти"))
        self.b_deleteProcImage0.setText(_translate("MainMenu", "X"))
        self.b_deleteOrigImage0.setText(_translate("MainMenu", "X"))
        self.b_show.setText(_translate("MainMenu", "+"))
        self.b_hide.setText(_translate("MainMenu", "-"))
        self.b_AddOrigImage0.setText(_translate("MainMenu", "+"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainMenu", "Генерація"))
        self.label_20.setText(_translate("MainMenu", "ДЕШИФРУВАННЯ"))
        self.b_ProcImageDecryptedText_2.setText(_translate("MainMenu", "Обробити фото"))
        self.te_DecryptedText_2.setHtml(_translate("MainMenu", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.b_deleteProcImageEnc.setText(_translate("MainMenu", "X"))
        self.b_SaveProcImageEnc.setText(_translate("MainMenu", "Зберегти"))
        self.le_EncryptedText.setPlaceholderText(_translate("MainMenu", "Зашифрований текст"))
        self.label_19.setText(_translate("MainMenu", "ШИФРУВАННЯ"))
        self.b_ProcImageEncryptedText.setText(_translate("MainMenu", "Обробити фото"))
        self.b_deleteOrigImageEnc.setText(_translate("MainMenu", "X"))
        self.b_AddOrigImageEnc.setText(_translate("MainMenu", "+"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainMenu", "Стеганографія"))
        self.label_9.setText(_translate("MainMenu", "Про Андрія:"))
        self.label_10.setText(_translate("MainMenu", "Про Софію:"))
        self.label_11.setText(_translate("MainMenu", "Про Руслана:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainMenu", "Інформація"))
        self.b_exit.setText(_translate("MainMenu", "Вийти"))
        self.la_username.setText(_translate("MainMenu", "Noname"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainMenu = QtWidgets.QMainWindow()
    ui = Ui_MainMenu()
    ui.setupUi(MainMenu)
    MainMenu.show()
    sys.exit(app.exec_())
